"""Add price and duration to Skill

Revision ID: 359c9d59f686
Revises: f83f8fc945e8
Create Date: 2025-09-05 14:22:14.336602

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '359c9d59f686'
down_revision = 'f83f8fc945e8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skill', schema=None) as batch_op:
        batch_op.add_column(sa.Column('price', sa.Float(), nullable=True))
        batch_op.add_column(sa.Column('duration', sa.Integer(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skill', schema=None) as batch_op:
        batch_op.drop_column('duration')
        batch_op.drop_column('price')

    # ### end Alembic commands ###
