"""Add gender, type, image_url to Skill

Revision ID: f83f8fc945e8
Revises: 94d164d44248
Create Date: 2025-09-05 14:15:19.736383

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f83f8fc945e8'
down_revision = '94d164d44248'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skill', schema=None) as batch_op:
        batch_op.add_column(sa.Column('gender', sa.String(length=10), nullable=False))
        batch_op.add_column(sa.Column('type', sa.String(length=100), nullable=True))
        batch_op.add_column(sa.Column('image_url', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('skill', schema=None) as batch_op:
        batch_op.drop_column('image_url')
        batch_op.drop_column('type')
        batch_op.drop_column('gender')

    # ### end Alembic commands ###
